// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://atlas.doroad.io/terms/",
        "contact": {
            "name": "Atlas API Support",
            "url": "https://github.com/DoROAD-AI/atlas/issues",
            "email": "support@doroad.ai"
        },
        "license": {
            "name": "MIT / Proprietary",
            "url": "https://github.com/DoROAD-AI/atlas/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/airports": {
            "get": {
                "description": "Retrieves a list of all airports for all countries (keyed by each country's alpha-2 code).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Airports"
                ],
                "summary": "Get all airports",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/v2.CountryAirports"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/airports/by-code/{airportCode}": {
            "get": {
                "description": "Retrieves a specific airport by its ICAO or IATA code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Airports"
                ],
                "summary": "Get airport by ICAO or IATA code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Airport ICAO or IATA code",
                        "name": "airportCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.Airport"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/airports/distance": {
            "get": {
                "description": "Calculates the distance (in kilometers and miles) between two airports.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Airports"
                ],
                "summary": "Calculate distance between two airports",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ICAO or IATA code of the first airport",
                        "name": "airport1",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ICAO or IATA code of the second airport",
                        "name": "airport2",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.AirportDistance"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/airports/keyword/{keyword}": {
            "get": {
                "description": "Retrieves all airports associated with a specific keyword.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Airports"
                ],
                "summary": "Get airports by keyword",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Keyword to search for",
                        "name": "keyword",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v2.Airport"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/airports/municipality/{municipalityName}": {
            "get": {
                "description": "Retrieves all airports within a specific municipality.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Airports"
                ],
                "summary": "Get airports by municipality",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Municipality name",
                        "name": "municipalityName",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v2.Airport"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/airports/radius": {
            "get": {
                "description": "Retrieves all airports within a specified radius of a given latitude/longitude coordinate.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Airports"
                ],
                "summary": "Get airports within a radius",
                "parameters": [
                    {
                        "type": "number",
                        "description": "Latitude of the center point",
                        "name": "latitude",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Longitude of the center point",
                        "name": "longitude",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Radius in kilometers",
                        "name": "radius",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v2.Airport"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/airports/region/{isoRegion}": {
            "get": {
                "description": "Retrieves all airports within a specific ISO region.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Airports"
                ],
                "summary": "Get airports by ISO region",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ISO region code (e.g., VC-04)",
                        "name": "isoRegion",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v2.Airport"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/airports/scheduled": {
            "get": {
                "description": "Retrieves all airports that have scheduled airline service.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Airports"
                ],
                "summary": "Get airports with scheduled service",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v2.Airport"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/airports/search": {
            "get": {
                "description": "Performs a flexible search for airports based on a query string.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Airports"
                ],
                "summary": "Search airports",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search string (can match airport name, city, ICAO/IATA code, etc.)",
                        "name": "query",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v2.Airport"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/airports/type/{airportType}": {
            "get": {
                "description": "Retrieves all airports of a specific type.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Airports"
                ],
                "summary": "Get airports by type",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Airport type (e.g., medium_airport, closed)",
                        "name": "airportType",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v2.Airport"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/airports/{countryCode}": {
            "get": {
                "description": "Retrieves all airports in a specific country. The country code can be in any recognized format (CCA2, CCA3, CCN3, CIOC, FIFA, or alt spelling).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Airports"
                ],
                "summary": "Get airports by country",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Country code (e.g., VC, VCT, 670, etc.)",
                        "name": "countryCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.CountryAirports"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/airports/{countryCode}/{airportIdent}": {
            "get": {
                "description": "Retrieves a specific airport within a country by matching the airport's ICAO or IATA code. The country code can be in any recognized format (CCA2, CCA3, CCN3, CIOC, etc.).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Airports"
                ],
                "summary": "Get a single airport by identifier",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Country code (e.g., VC, VCT, 670, etc.)",
                        "name": "countryCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Airport Ident (ICAO) or IATA code",
                        "name": "airportIdent",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.Airport"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/airports/{countryCode}/{airportIdent}/frequencies": {
            "get": {
                "description": "Retrieves communication frequencies used at a specific airport.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Airports"
                ],
                "summary": "Get airport frequencies",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Country code (e.g., VC, VCT, 670, etc.)",
                        "name": "countryCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Airport Ident (ICAO) or IATA code",
                        "name": "airportIdent",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v2.AirportFrequency"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/airports/{countryCode}/{airportIdent}/runways": {
            "get": {
                "description": "Retrieves detailed runway information for a specific airport.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Airports"
                ],
                "summary": "Get airport runways",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Country code (e.g., VC, VCT, 670, etc.)",
                        "name": "countryCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Airport Ident (ICAO) or IATA code",
                        "name": "airportIdent",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v2.AirportRunway"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/alpha": {
            "get": {
                "description": "Get countries matching a list of codes (CCA2, CCN3, CCA3, or CIOC).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Countries"
                ],
                "summary": "Get countries by codes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comma-separated list of country codes (CCA2, CCN3, CCA3, CIOC)",
                        "name": "codes",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of fields to include in the response",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Country"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/capital/{capital}": {
            "get": {
                "description": "Get countries matching a capital city name.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Countries"
                ],
                "summary": "Get countries by capital",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Capital city name",
                        "name": "capital",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of fields to include in the response",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Country"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ccn3/{code}": {
            "get": {
                "description": "Get details of a specific country by its numeric ISO code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Countries"
                ],
                "summary": "Get country by numeric ISO code (CCN3)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Numeric code (e.g., 840)",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of fields to include in the response",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Country"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/countries": {
            "get": {
                "description": "Get details of all countries, with optional filters.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Countries"
                ],
                "summary": "Get all countries",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by independent status (true or false)",
                        "name": "independent",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of fields to include in the response",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Country"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/countries/{code}": {
            "get": {
                "description": "Get details of a specific country by its code (CCA2 or CCA3).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Countries"
                ],
                "summary": "Get country by code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Country code (CCA2 or CCA3)",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of fields to include in the response",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Country"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/currency/{currency}": {
            "get": {
                "description": "Get countries matching a currency code or name.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Countries"
                ],
                "summary": "Get countries by currency",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Currency code or name",
                        "name": "currency",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of fields to include in the response",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Country"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/demonym/{demonym}": {
            "get": {
                "description": "Get countries matching a demonym.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Countries"
                ],
                "summary": "Get countries by demonym",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Demonym",
                        "name": "demonym",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of fields to include in the response",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Country"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/independent": {
            "get": {
                "description": "Get countries filtered by independence. Defaults to status=true if not specified.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Countries"
                ],
                "summary": "Get countries by independence status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "true or false. Defaults to 'true'",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of fields to include in the response",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Country"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lang/{language}": {
            "get": {
                "description": "Get countries matching a language code or name.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Countries"
                ],
                "summary": "Get countries by language",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Language code or name",
                        "name": "language",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of fields to include in the response",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Country"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/name/{name}": {
            "get": {
                "description": "Get countries matching a name query (common or official). Use fullText=true for exact name match.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Countries"
                ],
                "summary": "Get countries by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Country name (common or official)",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exact match for full name (true/false)",
                        "name": "fullText",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of fields to include in the response",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Country"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/passports/common-visa-free": {
            "get": {
                "description": "Determines the common countries that a set of passports can access visa-free.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Passports"
                ],
                "summary": "Find common visa-free destinations for multiple passports",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Comma-separated list of passport codes (e.g., USA,DEU,JPN)",
                        "name": "passports",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/passports/compare": {
            "get": {
                "description": "Compares visa requirements for a list of passports to a single destination.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Passports"
                ],
                "summary": "Compare visa requirements for multiple passports to a single destination",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Comma-separated list of passport codes (e.g., USA,DEU,JPN)",
                        "name": "passports",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Destination country code (e.g., FRA)",
                        "name": "destination",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/v2.VisaRequirement"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/passports/ranking": {
            "get": {
                "description": "Returns a ranked list of passports based on the number of countries they can access visa-free or with visa-on-arrival.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Passports"
                ],
                "summary": "Get a ranked list of passports based on visa-free access",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    }
                }
            }
        },
        "/passports/reciprocal/{countryCode1}/{countryCode2}": {
            "get": {
                "description": "Checks the visa requirements both ways between two countries.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Passports"
                ],
                "summary": "Get reciprocal visa requirements between two countries",
                "parameters": [
                    {
                        "type": "string",
                        "description": "First country code (e.g., USA, US, 840, etc.)",
                        "name": "countryCode1",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Second country code (e.g., DEU, DE, 276, etc.)",
                        "name": "countryCode2",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "$ref": "#/definitions/v2.VisaRequirement"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/passports/visa": {
            "get": {
                "description": "Get visa requirements for a passport holder from one country traveling to another.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Passports"
                ],
                "summary": "Get visa requirements between two countries",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Origin country code (e.g., USA, US, 840, etc.)",
                        "name": "fromCountry",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Destination country code (e.g., DEU, DE, 276, etc.)",
                        "name": "toCountry",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.VisaRequirement"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/passports/{passportCode}": {
            "get": {
                "description": "Get visa requirement data for a specific passport.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Passports"
                ],
                "summary": "Get passport data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Passport code (e.g., USA, US, 840, etc.)",
                        "name": "passportCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.PassportResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/passports/{passportCode}/e-visa": {
            "get": {
                "description": "Retrieves a list of countries where the given passport holder can apply for an e-visa.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Passports"
                ],
                "summary": "Get e-visa destinations for a passport",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Passport code (e.g., USA, US, 840, etc.)",
                        "name": "passportCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/passports/{passportCode}/visa-details/{destinationCode}": {
            "get": {
                "description": "Provides specific visa requirement details (duration, type, etc.) for a given passport and destination.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Passports"
                ],
                "summary": "Get detailed visa requirements for a passport and destination",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Passport code (e.g., USA, US, 840, etc.)",
                        "name": "passportCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Destination country code (e.g., DEU, DE, 276, etc.)",
                        "name": "destinationCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.VisaRequirement"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/passports/{passportCode}/visa-free": {
            "get": {
                "description": "Retrieves a list of countries where the given passport holder can travel visa-free.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Passports"
                ],
                "summary": "Get visa-free destinations for a passport",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Passport code (e.g., USA, US, 840, etc.)",
                        "name": "passportCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/passports/{passportCode}/visa-on-arrival": {
            "get": {
                "description": "Retrieves a list of countries where the given passport holder can obtain a visa on arrival.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Passports"
                ],
                "summary": "Get visa-on-arrival destinations for a passport",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Passport code (e.g., USA, US, 840, etc.)",
                        "name": "passportCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/passports/{passportCode}/visa-required": {
            "get": {
                "description": "Retrieves a list of countries where the given passport holder requires a visa before arrival.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Passports"
                ],
                "summary": "Get visa-required destinations for a passport",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Passport code (e.g., USA, US, 840, etc.)",
                        "name": "passportCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/passports/{passportCode}/visas": {
            "get": {
                "description": "Get visa requirements for all destinations for a specific passport.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Passports"
                ],
                "summary": "Get visa requirements for a passport",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Passport code (e.g., USA, US, 840, etc.)",
                        "name": "passportCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.PassportResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/region/{region}": {
            "get": {
                "description": "Get countries matching a region.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Countries"
                ],
                "summary": "Get countries by region",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Region name",
                        "name": "region",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of fields to include in the response",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Country"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/search": {
            "get": {
                "description": "Performs a comprehensive search across all data types (countries, airports) based on query parameters.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Search"
                ],
                "summary": "Super Type Query",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Type of data to search for (country, airport). If omitted or set to 'all', searches across all data types.",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Name of the country or airport",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Region of the country",
                        "name": "region",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Subregion of the country",
                        "name": "subregion",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Country code Alpha-2",
                        "name": "cca2",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Country code Alpha-3",
                        "name": "cca3",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Country code Numeric",
                        "name": "ccn3",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Capital city of the country",
                        "name": "capital",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Airport Ident code (e.g., ICAO code)",
                        "name": "ident",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Airport IATA code",
                        "name": "iata_code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ISO country code for airports",
                        "name": "iso_country",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ISO region code for airports",
                        "name": "iso_region",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Municipality of the airport",
                        "name": "municipality",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Type of the airport",
                        "name": "airport_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subregion/{subregion}": {
            "get": {
                "description": "Get countries matching a subregion.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Countries"
                ],
                "summary": "Get countries by subregion",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Subregion name",
                        "name": "subregion",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of fields to include in the response",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Country"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/translation/{translation}": {
            "get": {
                "description": "Get countries matching a translation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Countries"
                ],
                "summary": "Get countries by translation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Translation",
                        "name": "translation",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of fields to include in the response",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Country"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "v1.CapitalInfo": {
            "type": "object",
            "properties": {
                "latlng": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    },
                    "example": [
                        38.8951,
                        77.0364
                    ]
                }
            }
        },
        "v1.Car": {
            "type": "object",
            "properties": {
                "side": {
                    "type": "string",
                    "example": "right"
                },
                "signs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "USA"
                    ]
                }
            }
        },
        "v1.CoatOfArms": {
            "type": "object",
            "properties": {
                "png": {
                    "type": "string",
                    "example": "https://mainfacts.com/media/images/coats_of_arms/us.png"
                },
                "svg": {
                    "type": "string",
                    "example": "https://mainfacts.com/media/images/coats_of_arms/us.svg"
                }
            }
        },
        "v1.Country": {
            "type": "object",
            "properties": {
                "altSpellings": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "area": {
                    "type": "number",
                    "example": 9372610
                },
                "borders": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "capital": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Washington",
                        " D.C."
                    ]
                },
                "capitalInfo": {
                    "$ref": "#/definitions/v1.CapitalInfo"
                },
                "car": {
                    "$ref": "#/definitions/v1.Car"
                },
                "cca2": {
                    "type": "string",
                    "example": "US"
                },
                "cca3": {
                    "type": "string",
                    "example": "USA"
                },
                "ccn3": {
                    "type": "string",
                    "example": "840"
                },
                "cioc": {
                    "type": "string",
                    "example": "USA"
                },
                "coatOfArms": {
                    "$ref": "#/definitions/v1.CoatOfArms"
                },
                "continents": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "currencies": {
                    "$ref": "#/definitions/v1.Currencies"
                },
                "demonyms": {
                    "$ref": "#/definitions/v1.Demonyms"
                },
                "fifa": {
                    "type": "string",
                    "example": "USA"
                },
                "flag": {
                    "type": "string",
                    "example": "🇺🇸"
                },
                "flags": {
                    "$ref": "#/definitions/v1.Flags"
                },
                "gini": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number"
                    }
                },
                "idd": {
                    "$ref": "#/definitions/v1.IDD"
                },
                "independent": {
                    "type": "boolean",
                    "example": true
                },
                "landlocked": {
                    "type": "boolean",
                    "example": false
                },
                "languages": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "latlng": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "maps": {
                    "$ref": "#/definitions/v1.Maps"
                },
                "name": {
                    "$ref": "#/definitions/v1.Name"
                },
                "population": {
                    "type": "integer",
                    "example": 334805269
                },
                "postalCode": {
                    "$ref": "#/definitions/v1.PostalCode"
                },
                "region": {
                    "type": "string",
                    "example": "Americas"
                },
                "startOfWeek": {
                    "type": "string",
                    "example": "sunday"
                },
                "status": {
                    "type": "string",
                    "example": "officially-assigned"
                },
                "subregion": {
                    "type": "string",
                    "example": "North America"
                },
                "timezones": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tld": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "translations": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "object",
                        "properties": {
                            "common": {
                                "type": "string"
                            },
                            "official": {
                                "type": "string"
                            }
                        }
                    }
                },
                "unMember": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "v1.Currencies": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/v1.CurrencyInfo"
            }
        },
        "v1.CurrencyInfo": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "US Dollar"
                },
                "symbol": {
                    "type": "string",
                    "example": "$"
                }
            }
        },
        "v1.DemonymInfo": {
            "type": "object",
            "properties": {
                "f": {
                    "type": "string",
                    "example": "American"
                },
                "m": {
                    "type": "string",
                    "example": "American"
                }
            }
        },
        "v1.Demonyms": {
            "type": "object",
            "properties": {
                "eng": {
                    "$ref": "#/definitions/v1.DemonymInfo"
                },
                "fra": {
                    "$ref": "#/definitions/v1.DemonymInfo"
                }
            }
        },
        "v1.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Bad request"
                }
            }
        },
        "v1.Flags": {
            "type": "object",
            "properties": {
                "alt": {
                    "type": "string",
                    "example": "Flag of the United States"
                },
                "png": {
                    "type": "string",
                    "example": "https://restcountries.eu/data/usa.png"
                },
                "svg": {
                    "type": "string",
                    "example": "https://restcountries.eu/data/usa.svg"
                }
            }
        },
        "v1.IDD": {
            "type": "object",
            "properties": {
                "root": {
                    "type": "string",
                    "example": "+1"
                },
                "suffixes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "201",
                        "202"
                    ]
                }
            }
        },
        "v1.Maps": {
            "type": "object",
            "properties": {
                "googleMaps": {
                    "type": "string",
                    "example": "https://goo.gl/maps/..."
                },
                "openStreetMaps": {
                    "type": "string",
                    "example": "https://www.openstreetmap.org/..."
                }
            }
        },
        "v1.Name": {
            "type": "object",
            "properties": {
                "common": {
                    "type": "string",
                    "example": "United States"
                },
                "official": {
                    "type": "string",
                    "example": "United States of America"
                }
            }
        },
        "v1.PostalCode": {
            "type": "object",
            "properties": {
                "format": {
                    "type": "string",
                    "example": "#####-####"
                },
                "regex": {
                    "type": "string",
                    "example": "^\\d{5}(-\\d{4})?$"
                }
            }
        },
        "v2.Airport": {
            "description": "Airport represents the airport data.",
            "type": "object",
            "properties": {
                "comments": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        ""
                    ]
                },
                "continent": {
                    "type": "string",
                    "example": "NA"
                },
                "elevation_ft": {
                    "type": "string",
                    "example": "136"
                },
                "frequencies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v2.AirportFrequency"
                    }
                },
                "gps_code": {
                    "type": "string",
                    "example": "TVSA"
                },
                "home_link": {
                    "type": "string",
                    "example": "http://www.svgiadc.com"
                },
                "iata_code": {
                    "type": "string",
                    "example": "SVD"
                },
                "id": {
                    "type": "string",
                    "example": "322383"
                },
                "ident": {
                    "type": "string",
                    "example": "TVSA"
                },
                "iso_country": {
                    "type": "string",
                    "example": "VC"
                },
                "iso_region": {
                    "type": "string",
                    "example": "VC-04"
                },
                "keywords": {
                    "type": "string",
                    "example": ""
                },
                "latitude_deg": {
                    "type": "string",
                    "example": "13.156695"
                },
                "local_code": {
                    "type": "string",
                    "example": ""
                },
                "longitude_deg": {
                    "type": "string",
                    "example": "-61.149945"
                },
                "municipality": {
                    "type": "string",
                    "example": "Kingstown"
                },
                "name": {
                    "type": "string",
                    "example": "Argyle International Airport"
                },
                "runways": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v2.AirportRunway"
                    }
                },
                "scheduled_service": {
                    "type": "string",
                    "example": "yes"
                },
                "type": {
                    "type": "string",
                    "example": "medium_airport"
                },
                "wikipedia_link": {
                    "type": "string",
                    "example": "https://en.m.wikipedia.org/wiki/Argyle_International_Airport"
                }
            }
        },
        "v2.AirportDistance": {
            "description": "AirportDistance represents the distance between two airports.",
            "type": "object",
            "properties": {
                "airport1": {
                    "type": "string",
                    "example": "TVSA"
                },
                "airport2": {
                    "type": "string",
                    "example": "TVSB"
                },
                "distance_km": {
                    "type": "number",
                    "example": 1234.5
                },
                "distance_miles": {
                    "type": "number",
                    "example": 767.1
                }
            }
        },
        "v2.AirportFrequency": {
            "description": "AirportFrequency represents the frequency data for an airport.",
            "type": "object",
            "properties": {
                "airport_ident": {
                    "type": "string",
                    "example": "TVSA"
                },
                "airport_ref": {
                    "type": "string",
                    "example": "322383"
                },
                "description": {
                    "type": "string",
                    "example": "Argyle Approach"
                },
                "frequency_mhz": {
                    "type": "string",
                    "example": "120.8"
                },
                "id": {
                    "type": "string",
                    "example": "322388"
                },
                "type": {
                    "type": "string",
                    "example": "APP"
                }
            }
        },
        "v2.AirportRunway": {
            "description": "AirportRunway represents the runway data for an airport.",
            "type": "object",
            "properties": {
                "airport_ident": {
                    "type": "string",
                    "example": "TVSA"
                },
                "airport_ref": {
                    "type": "string",
                    "example": "322383"
                },
                "closed": {
                    "type": "string",
                    "example": "0"
                },
                "he_displaced_threshold_ft": {
                    "type": "string",
                    "example": "985"
                },
                "he_elevation_ft": {
                    "type": "string",
                    "example": "52"
                },
                "he_heading_degT": {
                    "type": "string",
                    "example": ""
                },
                "he_ident": {
                    "type": "string",
                    "example": "22"
                },
                "he_latitude_deg": {
                    "type": "string",
                    "example": ""
                },
                "he_longitude_deg": {
                    "type": "string",
                    "example": ""
                },
                "id": {
                    "type": "string",
                    "example": "322384"
                },
                "le_displaced_threshold_ft": {
                    "type": "string",
                    "example": ""
                },
                "le_elevation_ft": {
                    "type": "string",
                    "example": "136"
                },
                "le_heading_degT": {
                    "type": "string",
                    "example": ""
                },
                "le_ident": {
                    "type": "string",
                    "example": "04"
                },
                "le_latitude_deg": {
                    "type": "string",
                    "example": ""
                },
                "le_longitude_deg": {
                    "type": "string",
                    "example": ""
                },
                "length_ft": {
                    "type": "string",
                    "example": "9000"
                },
                "lighted": {
                    "type": "string",
                    "example": "1"
                },
                "surface": {
                    "type": "string",
                    "example": "ASP"
                },
                "width_ft": {
                    "type": "string",
                    "example": "148"
                }
            }
        },
        "v2.CountryAirports": {
            "description": "CountryAirports represents the airport data for a country.",
            "type": "object",
            "properties": {
                "airports": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v2.Airport"
                    }
                },
                "code": {
                    "type": "string",
                    "example": "VC"
                },
                "continent": {
                    "type": "string",
                    "example": "NA"
                },
                "id": {
                    "type": "string",
                    "example": "302756"
                },
                "keywords": {
                    "type": "string",
                    "example": "Airports in Saint Vincent and the Grenadines"
                },
                "name": {
                    "type": "string",
                    "example": "Saint Vincent and the Grenadines"
                },
                "wikipedia_link": {
                    "type": "string",
                    "example": "https://en.wikipedia.org/wiki/Saint_Vincent_and_the_Grenadines"
                }
            }
        },
        "v2.ErrorResponse": {
            "description": "ErrorResponse represents an error response.",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Bad request"
                }
            }
        },
        "v2.PassportResponse": {
            "description": "PassportResponse represents the passport data response.",
            "type": "object",
            "properties": {
                "passport": {
                    "type": "string",
                    "example": "USA"
                },
                "visas": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "v2.VisaRequirement": {
            "description": "VisaRequirement represents the visa requirement between two countries.",
            "type": "object",
            "properties": {
                "from": {
                    "type": "string",
                    "example": "USA"
                },
                "requirement": {
                    "type": "string",
                    "example": "90"
                },
                "to": {
                    "type": "string",
                    "example": "DEU"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "/v2",
	Schemes:          []string{"https", "http"},
	Title:            "Atlas - Global Travel and Aviation Intelligence Data API by DoROAD",
	Description:      "Atlas is DoROAD's flagship Global Travel and Aviation Intelligence Data API. Version 2.0 represents a significant leap forward, providing a comprehensive, high-performance RESTful API for accessing detailed country information, extensive airport data, and up-to-date passport visa requirements worldwide. This service offers extensive data about countries (demographics, geography, international codes, etc.), airports, and visa regulations for various passports.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
