// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://atlas.doroad.io/terms/",
        "contact": {
            "name": "Atlas API Support",
            "url": "https://github.com/DoROAD-AI/atlas/issues",
            "email": "support@doroad.ai"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/DoROAD-AI/atlas/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/airports": {
            "get": {
                "description": "Retrieves a list of all airports.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Airports"
                ],
                "summary": "Get all airports",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v2.CountryAirports"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/airports/country/{countryCode}": {
            "get": {
                "description": "Retrieves all airports in a specific country.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Airports"
                ],
                "summary": "Get airports by country",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Country code (e.g., VC)",
                        "name": "countryCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.CountryAirports"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/airports/{code}": {
            "get": {
                "description": "Retrieves an airport by its IATA or ICAO code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Airports"
                ],
                "summary": "Get airport by code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Airport code (IATA or ICAO)",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.Airport"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/alpha": {
            "get": {
                "description": "Get countries matching a list of codes (CCA2, CCN3, CCA3, or CIOC).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Countries"
                ],
                "summary": "Get countries by codes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comma-separated list of country codes (CCA2, CCN3, CCA3, CIOC)",
                        "name": "codes",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of fields to include in the response",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Country"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/capital/{capital}": {
            "get": {
                "description": "Get countries matching a capital city name.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Countries"
                ],
                "summary": "Get countries by capital",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Capital city name",
                        "name": "capital",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of fields to include in the response",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Country"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ccn3/{code}": {
            "get": {
                "description": "Get details of a specific country by its numeric ISO code.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Countries"
                ],
                "summary": "Get country by numeric ISO code (CCN3)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Numeric code (e.g., 840)",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of fields to include in the response",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Country"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/countries": {
            "get": {
                "description": "Get details of all countries, with optional filters.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Countries"
                ],
                "summary": "Get all countries",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by independent status (true or false)",
                        "name": "independent",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of fields to include in the response",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Country"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/countries/{code}": {
            "get": {
                "description": "Get details of a specific country by its code (CCA2 or CCA3).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Countries"
                ],
                "summary": "Get country by code",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Country code (CCA2 or CCA3)",
                        "name": "code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of fields to include in the response",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.Country"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/currency/{currency}": {
            "get": {
                "description": "Get countries matching a currency code or name.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Countries"
                ],
                "summary": "Get countries by currency",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Currency code or name",
                        "name": "currency",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of fields to include in the response",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Country"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/demonym/{demonym}": {
            "get": {
                "description": "Get countries matching a demonym.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Countries"
                ],
                "summary": "Get countries by demonym",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Demonym",
                        "name": "demonym",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of fields to include in the response",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Country"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/independent": {
            "get": {
                "description": "Get countries filtered by independence. Defaults to status=true if not specified.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Countries"
                ],
                "summary": "Get countries by independence status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "true or false. Defaults to 'true'",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of fields to include in the response",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Country"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/lang/{language}": {
            "get": {
                "description": "Get countries matching a language code or name.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Countries"
                ],
                "summary": "Get countries by language",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Language code or name",
                        "name": "language",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of fields to include in the response",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Country"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/name/{name}": {
            "get": {
                "description": "Get countries matching a name query (common or official). Use fullText=true for exact name match.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Countries"
                ],
                "summary": "Get countries by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Country name (common or official)",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Exact match for full name (true/false)",
                        "name": "fullText",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of fields to include in the response",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Country"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/passports/visa": {
            "get": {
                "description": "Get visa requirements for a passport holder from one country traveling to another.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Passports"
                ],
                "summary": "Get visa requirements between two countries",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Origin country code (e.g., USA)",
                        "name": "fromCountry",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Destination country code (e.g., DEU)",
                        "name": "toCountry",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.VisaRequirement"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/passports/{passportCode}": {
            "get": {
                "description": "Get visa requirement data for a specific passport.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Passports"
                ],
                "summary": "Get passport data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Passport code (e.g., USA)",
                        "name": "passportCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.PassportResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/passports/{passportCode}/visas": {
            "get": {
                "description": "Get visa requirements for all destinations for a specific passport.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Passports"
                ],
                "summary": "Get visa requirements for a passport",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Passport code (e.g., USA)",
                        "name": "passportCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v2.PassportResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v2.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/region/{region}": {
            "get": {
                "description": "Get countries matching a region.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Countries"
                ],
                "summary": "Get countries by region",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Region name",
                        "name": "region",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of fields to include in the response",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Country"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subregion/{subregion}": {
            "get": {
                "description": "Get countries matching a subregion.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Countries"
                ],
                "summary": "Get countries by subregion",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Subregion name",
                        "name": "subregion",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of fields to include in the response",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Country"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/translation/{translation}": {
            "get": {
                "description": "Get countries matching a translation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Countries"
                ],
                "summary": "Get countries by translation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Translation",
                        "name": "translation",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated list of fields to include in the response",
                        "name": "fields",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/v1.Country"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "v1.CapitalInfo": {
            "type": "object",
            "properties": {
                "latlng": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    },
                    "example": [
                        38.8951,
                        77.0364
                    ]
                }
            }
        },
        "v1.Car": {
            "type": "object",
            "properties": {
                "side": {
                    "type": "string",
                    "example": "right"
                },
                "signs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "USA"
                    ]
                }
            }
        },
        "v1.CoatOfArms": {
            "type": "object",
            "properties": {
                "png": {
                    "type": "string",
                    "example": "https://mainfacts.com/media/images/coats_of_arms/us.png"
                },
                "svg": {
                    "type": "string",
                    "example": "https://mainfacts.com/media/images/coats_of_arms/us.svg"
                }
            }
        },
        "v1.Country": {
            "type": "object",
            "properties": {
                "altSpellings": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "area": {
                    "type": "number",
                    "example": 9372610
                },
                "borders": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "capital": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Washington",
                        " D.C."
                    ]
                },
                "capitalInfo": {
                    "$ref": "#/definitions/v1.CapitalInfo"
                },
                "car": {
                    "$ref": "#/definitions/v1.Car"
                },
                "cca2": {
                    "type": "string",
                    "example": "US"
                },
                "cca3": {
                    "type": "string",
                    "example": "USA"
                },
                "ccn3": {
                    "type": "string",
                    "example": "840"
                },
                "cioc": {
                    "type": "string",
                    "example": "USA"
                },
                "coatOfArms": {
                    "$ref": "#/definitions/v1.CoatOfArms"
                },
                "continents": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "currencies": {
                    "$ref": "#/definitions/v1.Currencies"
                },
                "demonyms": {
                    "$ref": "#/definitions/v1.Demonyms"
                },
                "fifa": {
                    "type": "string",
                    "example": "USA"
                },
                "flag": {
                    "type": "string",
                    "example": "🇺🇸"
                },
                "flags": {
                    "$ref": "#/definitions/v1.Flags"
                },
                "gini": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number"
                    }
                },
                "idd": {
                    "$ref": "#/definitions/v1.IDD"
                },
                "independent": {
                    "type": "boolean",
                    "example": true
                },
                "landlocked": {
                    "type": "boolean",
                    "example": false
                },
                "languages": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "latlng": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "maps": {
                    "$ref": "#/definitions/v1.Maps"
                },
                "name": {
                    "$ref": "#/definitions/v1.Name"
                },
                "population": {
                    "type": "integer",
                    "example": 334805269
                },
                "postalCode": {
                    "$ref": "#/definitions/v1.PostalCode"
                },
                "region": {
                    "type": "string",
                    "example": "Americas"
                },
                "startOfWeek": {
                    "type": "string",
                    "example": "sunday"
                },
                "status": {
                    "type": "string",
                    "example": "officially-assigned"
                },
                "subregion": {
                    "type": "string",
                    "example": "North America"
                },
                "timezones": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tld": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "translations": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "object",
                        "properties": {
                            "common": {
                                "type": "string"
                            },
                            "official": {
                                "type": "string"
                            }
                        }
                    }
                },
                "unMember": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "v1.Currencies": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/v1.CurrencyInfo"
            }
        },
        "v1.CurrencyInfo": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "US Dollar"
                },
                "symbol": {
                    "type": "string",
                    "example": "$"
                }
            }
        },
        "v1.DemonymInfo": {
            "type": "object",
            "properties": {
                "f": {
                    "type": "string",
                    "example": "American"
                },
                "m": {
                    "type": "string",
                    "example": "American"
                }
            }
        },
        "v1.Demonyms": {
            "type": "object",
            "properties": {
                "eng": {
                    "$ref": "#/definitions/v1.DemonymInfo"
                },
                "fra": {
                    "$ref": "#/definitions/v1.DemonymInfo"
                }
            }
        },
        "v1.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Bad request"
                }
            }
        },
        "v1.Flags": {
            "type": "object",
            "properties": {
                "alt": {
                    "type": "string",
                    "example": "Flag of the United States"
                },
                "png": {
                    "type": "string",
                    "example": "https://restcountries.eu/data/usa.png"
                },
                "svg": {
                    "type": "string",
                    "example": "https://restcountries.eu/data/usa.svg"
                }
            }
        },
        "v1.IDD": {
            "type": "object",
            "properties": {
                "root": {
                    "type": "string",
                    "example": "+1"
                },
                "suffixes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "201",
                        "202"
                    ]
                }
            }
        },
        "v1.Maps": {
            "type": "object",
            "properties": {
                "googleMaps": {
                    "type": "string",
                    "example": "https://goo.gl/maps/..."
                },
                "openStreetMaps": {
                    "type": "string",
                    "example": "https://www.openstreetmap.org/..."
                }
            }
        },
        "v1.Name": {
            "type": "object",
            "properties": {
                "common": {
                    "type": "string",
                    "example": "United States"
                },
                "official": {
                    "type": "string",
                    "example": "United States of America"
                }
            }
        },
        "v1.PostalCode": {
            "type": "object",
            "properties": {
                "format": {
                    "type": "string",
                    "example": "#####-####"
                },
                "regex": {
                    "type": "string",
                    "example": "^\\d{5}(-\\d{4})?$"
                }
            }
        },
        "v2.Airport": {
            "description": "Airport represents the airport data.",
            "type": "object",
            "properties": {
                "comments": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        ""
                    ]
                },
                "continent": {
                    "type": "string",
                    "example": "NA"
                },
                "elevation_ft": {
                    "type": "string",
                    "example": "136"
                },
                "frequencies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v2.AirportFrequency"
                    }
                },
                "gps_code": {
                    "type": "string",
                    "example": "TVSA"
                },
                "home_link": {
                    "type": "string",
                    "example": "http://www.svgiadc.com"
                },
                "iata_code": {
                    "type": "string",
                    "example": "SVD"
                },
                "id": {
                    "type": "string",
                    "example": "322383"
                },
                "ident": {
                    "type": "string",
                    "example": "TVSA"
                },
                "iso_country": {
                    "type": "string",
                    "example": "VC"
                },
                "iso_region": {
                    "type": "string",
                    "example": "VC-04"
                },
                "keywords": {
                    "type": "string",
                    "example": ""
                },
                "latitude_deg": {
                    "type": "string",
                    "example": "13.156695"
                },
                "local_code": {
                    "type": "string",
                    "example": ""
                },
                "longitude_deg": {
                    "type": "string",
                    "example": "-61.149945"
                },
                "municipality": {
                    "type": "string",
                    "example": "Kingstown"
                },
                "name": {
                    "type": "string",
                    "example": "Argyle International Airport"
                },
                "runways": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v2.AirportRunway"
                    }
                },
                "scheduled_service": {
                    "type": "string",
                    "example": "yes"
                },
                "type": {
                    "type": "string",
                    "example": "medium_airport"
                },
                "wikipedia_link": {
                    "type": "string",
                    "example": "https://en.m.wikipedia.org/wiki/Argyle_International_Airport"
                }
            }
        },
        "v2.AirportFrequency": {
            "description": "AirportFrequency represents the frequency data for an airport.",
            "type": "object",
            "properties": {
                "airport_ident": {
                    "type": "string",
                    "example": "TVSA"
                },
                "airport_ref": {
                    "type": "string",
                    "example": "322383"
                },
                "description": {
                    "type": "string",
                    "example": "Argyle Approach"
                },
                "frequency_mhz": {
                    "type": "string",
                    "example": "120.8"
                },
                "id": {
                    "type": "string",
                    "example": "322388"
                },
                "type": {
                    "type": "string",
                    "example": "APP"
                }
            }
        },
        "v2.AirportRunway": {
            "description": "AirportRunway represents the runway data for an airport.",
            "type": "object",
            "properties": {
                "airport_ident": {
                    "type": "string",
                    "example": "TVSA"
                },
                "airport_ref": {
                    "type": "string",
                    "example": "322383"
                },
                "closed": {
                    "type": "string",
                    "example": "0"
                },
                "he_displaced_threshold_ft": {
                    "type": "string",
                    "example": "985"
                },
                "he_elevation_ft": {
                    "type": "string",
                    "example": "52"
                },
                "he_heading_degT": {
                    "type": "string",
                    "example": ""
                },
                "he_ident": {
                    "type": "string",
                    "example": "22"
                },
                "he_latitude_deg": {
                    "type": "string",
                    "example": ""
                },
                "he_longitude_deg": {
                    "type": "string",
                    "example": ""
                },
                "id": {
                    "type": "string",
                    "example": "322384"
                },
                "le_displaced_threshold_ft": {
                    "type": "string",
                    "example": ""
                },
                "le_elevation_ft": {
                    "type": "string",
                    "example": "136"
                },
                "le_heading_degT": {
                    "type": "string",
                    "example": ""
                },
                "le_ident": {
                    "type": "string",
                    "example": "04"
                },
                "le_latitude_deg": {
                    "type": "string",
                    "example": ""
                },
                "le_longitude_deg": {
                    "type": "string",
                    "example": ""
                },
                "length_ft": {
                    "type": "string",
                    "example": "9000"
                },
                "lighted": {
                    "type": "string",
                    "example": "1"
                },
                "surface": {
                    "type": "string",
                    "example": "ASP"
                },
                "width_ft": {
                    "type": "string",
                    "example": "148"
                }
            }
        },
        "v2.CountryAirports": {
            "description": "CountryAirports represents the airport data for a country.",
            "type": "object",
            "properties": {
                "airports": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/v2.Airport"
                    }
                },
                "code": {
                    "type": "string",
                    "example": "VC"
                },
                "continent": {
                    "type": "string",
                    "example": "NA"
                },
                "id": {
                    "type": "string",
                    "example": "302756"
                },
                "keywords": {
                    "type": "string",
                    "example": "Airports in Saint Vincent and the Grenadines"
                },
                "name": {
                    "type": "string",
                    "example": "Saint Vincent and the Grenadines"
                },
                "wikipedia_link": {
                    "type": "string",
                    "example": "https://en.wikipedia.org/wiki/Saint_Vincent_and_the_Grenadines"
                }
            }
        },
        "v2.ErrorResponse": {
            "description": "ErrorResponse represents an error response.",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Bad request"
                }
            }
        },
        "v2.PassportResponse": {
            "description": "PassportResponse represents the passport data response.",
            "type": "object",
            "properties": {
                "passport": {
                    "type": "string",
                    "example": "USA"
                },
                "visas": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "v2.VisaRequirement": {
            "description": "VisaRequirement represents the visa requirement between two countries.",
            "type": "object",
            "properties": {
                "from": {
                    "type": "string",
                    "example": "USA"
                },
                "requirement": {
                    "type": "string",
                    "example": "90"
                },
                "to": {
                    "type": "string",
                    "example": "DEU"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "/v2",
	Schemes:          []string{"https", "http"},
	Title:            "Atlas - Geographic and Passport Data API by DoROAD",
	Description:      "A comprehensive REST API providing detailed country information and passport visa requirements worldwide. This modern, high-performance service offers extensive data about countries, including demographics, geography, international codes, and visa regulations for various passports.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
